openapi: 3.0.3
info:
  title: STD24110
  version: 1.0.0
  servers:
  - url: http://localhost:8000
paths:
  /:
    get:
      summary: Root endpoint
      responses:
        '200':
          description: This is a specification of STD24110


      

